# .github/workflows/ci.yml
name: Rails CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gomoku_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/gomoku_test
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby 3.4.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.4
        bundler-cache: true
        working-directory: ./backend

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Install backend dependencies
      run: |
        cd backend
        bundle install

    - name: Set up database
      run: |
        cd backend
        bundle exec rails db:create
        bundle exec rails db:migrate

    - name: Run linting
      run: |
        cd backend
        bundle exec rubocop
        cd ../frontend
        npm run lint --if-present

    - name: Run unified test suite
      run: |
        cd backend
        bundle exec rake test:all

    - name: Build frontend
      run: |
        cd frontend
        npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to production
      run: |
        echo "🚀 Ready for deployment setup"
        echo "Frontend: Deploy to Vercel"
        echo "Backend: Deploy to Railway/Heroku"
